# Generated by Django 3.0.2 on 2020-01-22 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120)),
                ('room_name', models.CharField(max_length=30)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('booking_created_date', models.DateTimeField(auto_now_add=True)),
                ('booking_updated_date', models.DateTimeField(auto_now=True)),
                ('special_accomodations', models.CharField(max_length=500)),
                ('staff_member_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
