# Generated by Django 3.0.2 on 2020-01-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='booking_created_date',
            new_name='reservation_created_date',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='check_in_date',
            new_name='reservation_date',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='booking_updated_date',
            new_name='reservation_updated_date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='check_out_date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='room_name',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='special_accomodations',
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_time',
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='treatment',
            field=models.CharField(default='na', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='treatment_description',
            field=models.CharField(default='na', max_length=480),
            preserve_default=False,
        ),
    ]
